### ISSUE TITLE
Conflict MPTTModel and TransMeta

### ISSUE THREAD

**Issue by urtzai** [Yaco-Sistemas/django-transmeta#1]
I've got this issue: http://www.solutionoferror.com/python/conflict-mpttmodel-and-transmeta-in-django-34689.asp

Is there any solution to this conflict?

Thanks

**Comment by goinnn** [comment]
I don't know... both eggs use metaclasses. It's possible that with something like this works, but I don't know:

```
class MyMetaClass(MPTTModelBase, TransMeta):
    pass

class Item(models.Model):
     __metaclass__ = MyMetaClass
```

If this does not work, you have to code something... 

Please, tell me something if you find a solution.

If you can do a pull request :-)
