### ISSUE TITLE
sync_transmeta_db: There is no ALTER COLUMN in SQLite

### ISSUE THREAD

**Issue by goldan** [Yaco-Sistemas/django-transmeta#2]
Hello! I get the following error while doing 'sync_transmeta_db' for sqlite database:
SQL to synchronize "tags.tagcategory" schema:
   UPDATE "tags_tagcategory" SET "name_ru" = "name"
   ALTER TABLE "tags_tagcategory" ALTER COLUMN "name_ru" SET NOT NULL
   ALTER TABLE "tags_tagcategory" DROP COLUMN "name"
<...>
django.db.utils.OperationalError: near "ALTER": syntax error

It seems that sqlite does not have ALTER COLUMN statement: http://stackoverflow.com/questions/4007014/alter-column-in-sqlite

**Comment by goldan** [comment]
The same problem is with DROP COLUMN statement: 
ALTER TABLE "tags_tagcategory" DROP COLUMN "name";
Error: near "DROP": syntax error

http://stackoverflow.com/questions/8442147/how-to-delete-or-add-column-in-sqlite

**Comment by goinnn** [comment]
Yes @goldan. We know it. I'm sorry, but we are not interested in fix this bug, this will be a lot of work, we have to reimplement the command for sqlite. We use sync_transmeta_db command in the production servers, and we always use in these servers postgres or mysql.

Thanks you!!

If you do a pull request, I could see it... and I will merge it

**Comment by goldan** [comment]
Ok, no problem, I can use dumpdata/loaddata to workaround this. Thank you for the response and a great app!
